// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLabel: typeof import('element-plus/es')['ElLabel']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpPassoword: typeof import('~icons/ep/passoword')['default']
    IEpPassowrd: typeof import('~icons/ep/passowrd')['default']
    IEpPassword: typeof import('~icons/ep/password')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSetup: typeof import('~icons/ep/setup')['default']
    IEpSetUp: typeof import('~icons/ep/set-up')['default']
    IEpSetUp2: typeof import('~icons/ep/set-up2')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
